### ISSUE TITLE
Refactoring names in the implementation for API Models and implementation/endpoint functions

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#17]
Improve the names for the API Models and the functions names.

``Response`` ->  ``BootstrapResponse``
``get``  -> ``get_bootstrap``

**Comment by KAUTH** [comment]
Doing some cleanup:
- `BootstrapResponse` was changed to `BootstrapGetResponse` and `BootstrapPostResponse` accordingly in https://github.com/repository-service-tuf/repository-service-tuf-api/commit/d24b69bfd8d54c931d17bf6e40a4968ccbea4807#diff-8ce4883d268e87f0aaed768dbec3413cbbbdb442ca8788479f242e88665f0484
- `get_bootstrap` is also named as desired

@kairoaraujo I believe we can close this issue.
