### ISSUE TITLE
Bug: In case Bootstrap task has a failure, bootstrap is locked.

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#181]
### What happened?

Some error happened during the processing of the Bootstrap by the Worker (i.e.: OS Error)

```
repository-service-tuf-worker_1  | [2022-11-14 15:31:03,027: DEBUG/ForkPoolWorker-8] PRE_RUN: bf0522bc2f8347db9724e65ddf48a10e
repository-service-tuf-worker_1  | [2022-11-14 15:31:03,031: DEBUG/ForkPoolWorker-8] STORAGE_BACKEND is defined as <class 'repository_service_tuf_worker.services.storage.local.LocalStorage'>
repository-service-tuf-worker_1  | [2022-11-14 15:31:03,031: DEBUG/ForkPoolWorker-8] KEYVAULT_BACKEND is defined as <class 'repository_service_tuf_worker.services.keyvault.local.LocalKeyVault'>
repository-service-tuf-worker_1  | [2022-11-14 15:31:03,289: ERROR/ForkPoolWorker-8] Task app.repository_service_tuf_worker[bf0522bc2f8347db9724e65ddf48a10e] raised unexpected: OSError("Permission Denied")
```
I cannot process the Bootstrap again. The system is locked for bootstrap.
```json
{
  "data": {
    "bootstrap": true
  },
  "message": "System LOCKED for bootstrap."
}
```

### What steps did you take?

1. RSTUF was deployed successfully.
2. Ceremony + Bootstrap
3. Force some error/exception in the Worker (`repository_service_tuf_worker.repository.bootstrap`)
    i.e: raise OSError
5. The task will fail (`/api/v1/tasks`)
```
{
  "data": {
    "task_id": "bf0522bc2f8347db9724e65ddf48a10e",
    "state": "FAILURE",
    "result": "Invalid input of type: 'dict'. Convert to a bytes, string, int or float first."
  },
  "message": "Task state."
}
```

### What behavior did you expect?

If the bootstrap task fails, it shows the error to the user, like synchronous tasks for bootstrap.

**Possible solution:**
The procedure in the repository-service-tuf-api should do a call back to the task (as the rest API)
If it fails, update the BOOTSTRAP in Redis to NONE.

- https://github.com/vmware/repository-service-tuf-api/blob/main/repository_service_tuf_api/bootstrap.py#L264-L272

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
While investigating this issue I realized we need to make sure that we check that there are no metadata files already saved.
Meaning we need to catch any exceptions inside the worker, check if any of the metadata files are saved, delete them and rethrow the error again.
This will make sure that the next time we try to do `bootstrap` we can save the new files without any errors.
Also, it has the side benefit that it removes the confusion from the user because if a user sees that the bootstrap failed and we successfully remove the lock meaning the `api/v1/get/bootstrap` says the system is ready for bootstrap, but there are already existing metadata files it could be confusing for the user.

**Comment by MVrachev** [comment]
> While investigating this issue I realized we need to make sure that we check that there are no metadata files already saved. Meaning we need to catch any exceptions inside the worker, check if any of the metadata files are saved, delete them and rethrow the error again. This will make sure that the next time we try to do `bootstrap` we can save the new files without any errors. Also, it has the side benefit that it removes the confusion from the user because if a user sees that the bootstrap failed and we successfully remove the lock meaning the `api/v1/get/bootstrap` says the system is ready for bootstrap, but there are already existing metadata files it could be confusing for the user.
> 
> A simple solution to that will be to make sure we persist the metadata at the absolute end of the https://github.com/vmware/repository-service-tuf-worker/blob/5ac572a5d05558d915f3576e770490bc2e8bbd89/repository_service_tuf_worker/repository.py#L395 function.

I have created an issue for that: https://github.com/vmware/repository-service-tuf-worker/issues/248.
