### ISSUE TITLE
Task: remove "paths" attribute from "RoleSettings"

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-api#259]
### What is the task about?

We no longer need the `paths` attribute from https://github.com/vmware/repository-service-tuf-api/blob/94f4f4a3af7dc56c71342a3521b426dd8c27876c/repository_service_tuf_api/bootstrap.py#L124.
This change should be on top of the `feature/roles-simplification` branch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by deepgohil** [comment]
I would like to solve this issue

**Comment by MVrachev** [comment]
Awesome, go ahead.
Will assign you.

**Comment by deepgohil** [comment]
@MVrachev  I am getting this Error (Error: Process completed with exit code 255.) can you tell me how to solve this

**Comment by MVrachev** [comment]
Yes, I will comment on the pull request you have submitted.
Let's discuss code changes there.

**Comment by kairoaraujo** [comment]
Closed by #262
