### ISSUE TITLE
Task: Remove `sub`, `username` and `password` from returned `access_token`

### ISSUE THREAD

**Issue by KAUTH** [repository-service-tuf/repository-service-tuf-api#263]
### What is the task about?

The values of `sub`, `username` and `password` that are encoded in the `access_token` that is returned to the user for authentication/authorization (POST `/api/v1/token` or `/api/v1/token/new`) are not used to validate the token ([here](https://github.com/vmware/repository-service-tuf-api/blob/main/repository_service_tuf_api/token.py#L129)) or for any other reason, so they should be removed.
*The `username` could be potentially used in the future for authorization, but since now we only have one admin user it is not needed.*

Example payload of `access_token` now:
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzFfNjZjNzEyMGQxM2Q4NDRlY2E1ZDczNDA4NjBkNWM1OTIiLCJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJiJyQyYiQxMiRFZnltS1Y5RWdEeVZoLy5RSnEwaEl1NHdiV2J4M0JXa3VhbEFvLmRaUkpSNW5PRENvRjhCaSciLCJzY29wZXMiOlsicmVhZDpib290c3RyYXAiLCJyZWFkOnNldHRpbmdzIiwicmVhZDp0YXNrcyIsInJlYWQ6dG9rZW4iLCJ3cml0ZTpib290c3RyYXAiLCJ3cml0ZTp0YXJnZXRzIiwid3JpdGU6dG9rZW4iLCJkZWxldGU6dGFyZ2V0cyJdLCJleHAiOjIwMzY4Mzk1NjJ9.ko614QA9Ud3r3Y64O_a6jTIzxlm6PmI1M-hhuZNHZ7E
Decoded token payload:
```json
{
  "sub": "user_1_66c7120d13d844eca5d7340860d5c592",
  "username": "admin",
  "password": "b'$2b$12$EfymKV9EgDyVh/.QJq0hIu4wbWbx3BWkualAo.dZRJR5nODCoF8Bi'",
  "scopes": [
    "read:bootstrap",
    "read:settings",
    "read:tasks",
    "read:token",
    "write:bootstrap",
    "write:targets",
    "write:token",
    "delete:targets"
  ],
  "exp": 2036839562
}
```

Proposed decoded token payload will look like:
```json
{
  "scopes": [
    "read:bootstrap",
    "read:settings",
    "read:tasks",
    "read:token",
    "write:bootstrap",
    "write:targets",
    "write:token",
    "delete:targets"
  ],
  "exp": 2036839562
}
```

Let me know what you think, I'm opening a PR 😊

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
We don't use authentication and authorization anymore, so this could be closed.
