### ISSUE TITLE
Remove the unused output in workflow

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#272]
The `.github/workflows/cd.yml` doesn't use or set the `steps.api_version.outputs.VERSION` 
https://github.com/vmware/repository-service-tuf-api/blob/156f06bea30aca3c7c05e1aced883030419596b9/.github/workflows/cd.yml#L31

**Comment by fsavoia** [comment]
This issue is already done by this commit.

https://github.com/repository-service-tuf/repository-service-tuf-api/commit/f74de8613955ad25b44df6a27c39a2fe27cbcd1d

**Comment by kairoaraujo** [comment]
Thank you, @fsavoia. It is important to clean up our backlog.
Closing this issue.
