### ISSUE TITLE
Task: add integration tests for RSTUF API without authentication

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-api#312]
### What is the task about?

Add integration tests for RSTUF API without authentication.
This is more suitable than unit tests as it allows us to test the functionality better without using FAST API hacks to bypass security.

Those tests should be similar to the functional tests using an RSTUF API instance.

### Parent feature

- https://github.com/vmware/repository-service-tuf/issues/41

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
I think we can close this one as we have removed authorization already with issue https://github.com/repository-service-tuf/repository-service-tuf-api/issues/312, right @kairoaraujo?

**Comment by kairoaraujo** [comment]
That is right! Closing it.
