### ISSUE TITLE
Task: Implement FT tests when a PR is approved

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#319]
### What is the task about?

This issue aims to implement functional test (FT) checks when a PR has a review approved.

When a maintainer does the first approval for the PR, it will trigger the FT. I should use the "dev" version for all components.

### References

GitHub Workflow `CD.yml`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
This is done already.
