### ISSUE TITLE
Task: remove unnecessary root expiration from bootstrap and metadata update 

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-api#344]
### What is the task about?

Currently in the bootstrap payload and metadata rotation payloads we send information about root expiration:
- [bootstrap payload](https://github.com/repository-service-tuf/repository-service-tuf-api/blob/main/tests/data_examples/bootstrap/payload.json)
- [metadata update]()https://github.com/repository-service-tuf/repository-service-tuf-api/blob/main/tests/data_examples/metadata/update-root-payload.json)

This is not required as we don't automatically bump root expiry we only do that for all online roles or the rest of the roles.

**Important: fix will be required for RSTUF worker as well.**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
We shouldn't remove the information about root expiration from settings.
It is still a relevant configuration chosen by the user and is not stored in the root metadata (only when the Root metadata expires). Besides, we don't use it in the operation.

It gives a single place where he can retrieve all information about the expiration policy ``GET /api/v1/config``.

IMO, it gives the user complete TUF policy management, having all information about the settings of RSTUF. It can help corporations/organizations in their identity management, for example. They can integrate directly into our API and know not only when it will expire but also the expiration policy is chosen.

```json
{
  "data": {
    "bootstrap": "68a6c407a3b44cc78be3af4425d0e4a6",
    "root_expiration": 365,
    "root_threshold": 1,
    "root_num_keys": 2,
    "targets_expiration": 365,
    "targets_threshold": 1,
    "targets_num_keys": 1,
    "snapshot_expiration": 1,
    "snapshot_threshold": 1,
    "snapshot_num_keys": 1,
    "timestamp_expiration": 1,
    "timestamp_threshold": 1,
    "timestamp_num_keys": 1,
    "bins_expiration": 1,
    "bins_threshold": 1,
    "bins_num_keys": 1,
    "number_of_delegated_bins": 4,
    "targets_base_url": "http://www.example.com/repository/",
    "targets_online_key": true
  },
  "message": "Current Settings"
}
```

**Comment by MVrachev** [comment]
Okay, I see the need to send root expiration in bootstrap and metadata update.
It's good to have the opportunity for our users to see their past expiration policy for root and with the `GET /api/v1/config` they can do that for the whole RSTUF configuration.
Closing this issue.
