### ISSUE TITLE
Bug: `POST /api/v1/artifacts/` response's `message` value doesn't match docs

### ISSUE THREAD

**Issue by KAUTH** [repository-service-tuf/repository-service-tuf-api#405]
### What happened?

While querying the `POST /api/v1/artifacts/` resource I expected in the successful response a `message` value of `"New Target(s) successfully submitted."`. However, the `message` value is actually `Target(s) successfully submitted.`.
See https://github.com/repository-service-tuf/repository-service-tuf-api/blob/main/repository_service_tuf_api/targets.py#L151.

### What behavior did you expect?

A response `message` value of `"New Target(s) successfully submitted."` (expected according to the docs).

We should update the [docs](https://github.com/repository-service-tuf/repository-service-tuf-api/blob/main/repository_service_tuf_api/targets.py#L40) and code with the same `message` value.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
When updating the documentation, don't forget to run `make docs`.
