### ISSUE TITLE
Task: Update API task response documentation

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#406]
### What is the task about?

This task is about updating the API task response body documentation in https://github.com/repository-service-tuf/repository-service-tuf-api/blob/47af69507a4cdcedaa53453dd44e75f8043f0caa/repository_service_tuf_api/tasks.py#L21-L29

The new documentation needs to adhere to the new task status response standard that was [implemented by the worker from v0.7.0b1](https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/349/commits/29bc0a02eeaabfd21247740bd5eee277e91fe4bb).

Also, include a correct example on https://github.com/repository-service-tuf/repository-service-tuf-api/blob/47af69507a4cdcedaa53453dd44e75f8043f0caa/repository_service_tuf_api/tasks.py#L36-L46

Moving the specific description about the `state`
https://github.com/repository-service-tuf/repository-service-tuf-api/blob/47af69507a4cdcedaa53453dd44e75f8043f0caa/repository_service_tuf_api/api/tasks.py#L22-L31
 to the body, documentation might be a nice choice to https://github.com/repository-service-tuf/repository-service-tuf-api/blob/47af69507a4cdcedaa53453dd44e75f8043f0caa/repository_service_tuf_api/tasks.py#L23-L25
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fsavoia** [comment]
Can you assign this task to me? Thank you.

**Comment by MVrachev** [comment]
It seems that @kairoaraujo  already proposed a pr.
It seems that Kairo started working on this one without assigning himself which led to confusion.

**Comment by kairoaraujo** [comment]
Yes, I mentioned it to @fsavoia in Slack.
It is the same issue related to the RubyGems PR.
