### ISSUE TITLE
Task: rename other enum members to UPPER_CASE to follow convention

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-api#413]
### What is the task about?

We have discussed with Kairo that we prefer if enum values are UPPER_CASE the same way as constants are:
https://peps.python.org/pep-0008/#constants
I have made similar changes here: https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/356

It's good to check if there are other places with such naming inconsistencies, but one enum class with such an inconsistency is this one: https://github.com/repository-service-tuf/repository-service-tuf-api/blob/0c008b958cb3aefd9cbd8ecac0e47cdb1599b7de/repository_service_tuf_api/__init__.py#L54-L64

From RSTUF CLI we have that problem with:
- https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/9a7643c872fafac74cd36fe99a76b85c007ccec5/repository_service_tuf/helpers/api_client.py#L19
- https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/9a7643c872fafac74cd36fe99a76b85c007ccec5/repository_service_tuf/helpers/api_client.py#L28

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muhahahmad68** [comment]
Kindly assign this to me

**Comment by MVrachev** [comment]
Done!
Thanks for picking issues from RSTUF and helping us!

**Comment by MVrachev** [comment]
There are possible other enum classes that could be renamed as well.
Have a look.
That could allow you to get familiar more with the code.

**Comment by muhahahmad68** [comment]
A few questions, @MVrachev 
I couldn't find the exact file, should I go through the files and make the necessary changes as said?

**Comment by MVrachev** [comment]
Oohh, yes, now I remembred we deleted this enum class in this pr:
https://github.com/repository-service-tuf/repository-service-tuf-api/pull/470/files#diff-cdf19a48d719aefc0338056f418ab6abb8109067a78f041dbb2b26ff3c2bc713

Still, can you rename this enum class instead:
https://github.com/repository-service-tuf/repository-service-tuf-api/blob/9f3fc28361619118d4c950b55045a780354b53db/repository_service_tuf_api/common_models.py#L11

**Comment by muhahahmad68** [comment]
Much thanks.

**Comment by muhahahmad68** [comment]
@MVrachev , Kindly unassign me.
Apologies.
I'm having some difficulties with the project

**Comment by MVrachev** [comment]
No problem.
I thank you for your work!

I am open for meeting online if you want help.
Otherwise now I will unassign you.

**Comment by muhahahmad68** [comment]
I don't mind a meeting
What time would you be available?

**Comment by muhahahmad68** [comment]
Should I still be expecting a response @MVrachev ?

**Comment by MVrachev** [comment]
Please join Linux Foundation Slack workspace: https://join.slack.com/t/openssf/shared_invite/zt-26ps354o0-IPr1hRQtoyfmKEkxrmXXXg and there find me under the name `Martin Vrachev`. There we can arrange a meeting. 

There you can also follow our channel ``repository-sercice-tuf` where you can follow news about this project.

**Comment by MVrachev** [comment]
Superseded by: https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/442
