### ISSUE TITLE
Task: add more information in the response of `GET /api/v1/bootstrap`

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-api#416]
### What is the task about?

Add more information in the response of `GET /api/v1/bootstrap` like:
1. the bootstrap status along with an explanation. What do we return when `BOOTSTRAP` is `pre-<task id>` or `signing-<task id>`? 
2. if `BOOTSTRAP` is in the middle of a DAS process or `signing-<task id>` then mention how many signatures more are required and which keys can be used

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YuYuan-Chang** [comment]
For the 1 question, pre-<task id> mean Initial process and signing-<task id> mean Signing process, but what should we return for this given BOOTSTRAP state? What information are you excepting?

**Comment by kairoaraujo** [comment]
I think the idea is that [`BOOTSTRAP` stays as a boolean](https://repository-service-tuf.github.io/repository-service-tuf-api/#/v1/get_api_v1_bootstrap__get ).

Introduce the `state`, which will contain `None`, `pre`, `signing`, `finished` [based on the TUF Repository Settings design]
(https://repository-service-tuf.readthedocs.io/en/stable/devel/design.html#tuf-repository-settings).

Introduce the `Optional` `id` that will contains the task id

Introduce `Optional` `details` or even use the `message` to be descriptive about remaining keys, etc.

**Comment by jaydeep138** [comment]
I am working on this issue.

**Comment by MVrachev** [comment]
@jaydeep138 @YuYuan-Chang have you had a look at that issue?
Would you have time this or next week to work on it?
Asking as we want this issue to be fixed soon.

**Comment by MVrachev** [comment]
I don't see what is remaining to be added as I think we did that already.
See: https://github.com/repository-service-tuf/repository-service-tuf-api/blob/6c681663f17a9f23fd8dac640ed6ffc5bdf8d649/repository_service_tuf_api/bootstrap.py#L76-L84.
@kairoaraujo do you see the need of any other changes or we can close that one?

**Comment by kairoaraujo** [comment]
> @kairoaraujo do you see the need of any other changes or we can close that one?

We can close it :)
