### ISSUE TITLE
Task: Refactor method DELETE /api/v1/artifacts to POST /api/v1/artifacts/delete

### ISSUE THREAD

**Issue by enyinna1234** [repository-service-tuf/repository-service-tuf-api#462]
### What is the task about?

The `DELETE` `/api/v1/artifacts` method will be changed to `POST` `/api/v1/artifacts/delete`.

### Parent feature

- https://github.com/repository-service-tuf/repository-service-tuf-api/issues/455

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Closed by 
- https://github.com/repository-service-tuf/repository-service-tuf-api/pull/469

**Comment by MVrachev** [comment]
In a conversation with @kairoaraujo we realized that this is not yet closed.
