### ISSUE TITLE
Task: Update the Guide "Removing Targets Artifacts"

### ISSUE THREAD

**Issue by enyinna1234** [repository-service-tuf/repository-service-tuf-api#463]
### What is the task about?

Make the necessary changes to the documentation after `DELETE` `/api/v1/artifacts` changes to `POST` `/api/v1/artifacts/delete`.

### Parent feature

https://github.com/repository-service-tuf/repository-service-tuf-api/issues/455

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Closing as this change is on the Umbrella repository.
I opened an issue in the correct repository
-  https://github.com/repository-service-tuf/repository-service-tuf/issues/502
