### ISSUE TITLE
Task: Update the CLI command

### ISSUE THREAD

**Issue by enyinna1234** [repository-service-tuf/repository-service-tuf-api#465]
### What is the task about?

Update the RSTUF CLI command rstuf admin metadata sign --delete to use the new /api/v1/sign/deleteendpoint and method post.

### Parent feature

https://github.com/repository-service-tuf/repository-service-tuf-api/issues/455

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
Closing this issue as the task is for CLI (repository-service-tuf/repository-service-tuf-cli)
The new issue is opened:
- https://github.com/repository-service-tuf/repository-service-tuf-cli/issues/409
