### ISSUE TITLE
Bug: Inconsistency on the initial task result missing `last_update`

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#471]
I notice that we have some inconsistency in the initial task result.

The example below shows when submitting a `metadata_update` task, it shows only the task ID on the initial response/state.

https://github.com/repository-service-tuf/repository-service-tuf-api/blob/d552d0f74a0b3454f535c94a71029524479b4e3a/repository_service_tuf_api/metadata.py#L76-L80

A good practice would be to have at least the `last_update` and maybe `state` as `SUBMITTED`.

A good (not perfect) reference is the add/remove targets.

https://github.com/repository-service-tuf/repository-service-tuf-api/blob/d552d0f74a0b3454f535c94a71029524479b4e3a/repository_service_tuf_api/targets.py#L153-L160

**Comment by fsavoia** [comment]
@kairoaraujo , if you agree, can you assign this task to me? Thanks
