### ISSUE TITLE
Task: Implement GH workflow for automated pre-commit hook update

### ISSUE THREAD

**Issue by KAUTH** [repository-service-tuf/repository-service-tuf-api#479]
### What is the task about?

Following the example of https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/main/.github/workflows/update-pre-commit-hooks.yml, add a GitHub workflow that automates the updating of the `pre-commit` hooks in the `.pre-commit-config.yaml` file.

### References

- https://docs.github.com/en/actions/using-workflows
- https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/main/.github/workflows/update-pre-commit-hooks.yml
- https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/383

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by muhahahmad68** [comment]
Hi, @KAUTH kindly assign this to me

**Comment by muhahahmad68** [comment]
Hi @KAUTH, I sent a PR on this issue, kindly help me go through.
