### ISSUE TITLE
Task: document which of the endpoints are synchronous and which are asynchronous

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-api#484]
### What is the task about?

Document which of the endpoints are synchronous and which are asynchronous.
Then run `make run-dev` and make sure documentation is updated.

### References:

- Discussion on the topic: https://openssf.slack.com/archives/C052QF5CZFH/p1697794905106449
- API documentation: https://repository-service-tuf.github.io/repository-service-tuf-api/#/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fsavoia** [comment]
Hi, can you assign this task to me? Thank you.

**Comment by MVrachev** [comment]
Welcome :)

**Comment by kairoaraujo** [comment]
@simi FYI 🎉
