### ISSUE TITLE
Task: change `state` value if worker task result has a `status = False`

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-api#515]
### What is the task about?

This is a request coming from RubyGems maintainers that it would be better and easier for them if they can understand that a task has failed or errored based on the returned `state` instead of parsing the result and checking the `status`.
This will also improve all future clients.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fsavoia** [comment]
Hi @MVrachev, can you assign this to me?
