### ISSUE TITLE
dev: replace `docker-compose` to `docker compose`

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#716]
https://github.com/repository-service-tuf/repository-service-tuf-api/blob/ba2190f647c86456b4f1b41236c383e6a3c604e7/Makefile#L38

Please verify the other project repositories as well
- https://github.com/repository-service-tuf/repository-service-tuf-worker
- https://github.com/repository-service-tuf/repository-service-tuf-cli
- https://github.com/repository-service-tuf/repository-service-tuf

**Comment by sikehish** [comment]
I'd like to take this up. Could you assign this to me?

**Comment by Brijeshthummar02** [comment]
i would love to do it, @kairoaraujo assign me.

**Comment by kairoaraujo** [comment]
Thank you folks. 
First in first served. 😅

@Brijeshthummar02 check out this one https://github.com/repository-service-tuf/repository-service-tuf-api/issues/717

There are many good first issue in the https://github.com/repository-service-tuf/repository-service-tuf-cli/issues too.

**Comment by sikehish** [comment]
> Thank you folks. First in first served. 😅
> 
> @Brijeshthummar02 check out this one #717
> 
> There are many good first issue in the https://github.com/repository-service-tuf/repository-service-tuf-cli/issues too.
Hi, @kairoaraujo. 
I have made the modification. Let me know if any other changes are to be made :))
