### ISSUE TITLE
build: use single Python Version for API container CI/CD and tox

### ISSUE THREAD

**Issue by kairoaraujo** [repository-service-tuf/repository-service-tuf-api#717]
### What is the task about?

RSTUF API is provided as a Container Image.

Currently, we support during the tests (tox) and CI/CD process (Github Actions) multiple versions.
It is not required, as we build the image using Python version 3.12.

We can remove all the previous versions and operate with one specific version (3.12).

Se the reference below.

### References

https://github.com/repository-service-tuf/repository-service-tuf-worker/pull/629/commits/8f8412521a6be89b6ff3eb8c1012d23f96564d81

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Brijeshthummar02** [comment]
@kairoaraujo i would like to take the issue, assign me.

**Comment by Brijeshthummar02** [comment]
need your help, as i'm not able to locate some of the files can you show me the path to file.

**Comment by kairoaraujo** [comment]
> need your help, as i'm not able to locate some of the files can you show me the path to file.

Which files you can't find?
See the PR commit I added in the issue as a reference (different project)

**Comment by Brijeshthummar02** [comment]
docker-compose-aws.yml, docker-compose-mysql.yml, docker-compose-redis.yml. this 3 files i'm not able to locate.

**Comment by Brijeshthummar02** [comment]
@kairoaraujo above mention files are in [repository-service-tuf-worker](https://github.com/repository-service-tuf/repository-service-tuf-worker), how would i create pr in this repo, as those files exist in another repo. 
indeed guide needed.

**Comment by kairoaraujo** [comment]
It is just a reference. It does not mean that the API has all the same files.
Those files are not part of API.

**Comment by kairoaraujo** [comment]
> So i only need to change Python version 3.12. in those files which are there in this current repo. am i right?

Yes, that is correct.
